### ISSUE TITLE
Use KeyStore to create user account

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#17]

**Comment by Peppermint1020** [comment]
This function is complete in the dev mode android version vDebug. The vision of test phone is Android 17. 

User can create account by input user name, and seed phrase will not shown until backup stage. 

The create account process is attached below.


https://github.com/Outblock/FRW-Android/assets/87978227/d9255892-aef1-4e16-aecc-4dbc8fe8a67c
