### ISSUE TITLE
[BUG] Ensure Full Amount is Sent When Moving or Sending Max Amount FT

### ISSUE THREAD

**Issue by Peppermint1020** [Outblock/FRW-Android#398]
Description:
When attempting to move or send the maximum amount of fungible tokens (FT), the application should ensure that the full amount is sent without any rounding issues. Currently, the precision for sending the maximum amount of tokens on iOS is limited to three decimal places.

Steps to Reproduce:

(1) Open the application and navigate to the transfer or move tokens section.
(2) Select the option to send the maximum amount of FT.
(3) Confirm the transaction.

Expected Behavior:
The application should accurately calculate and send the full amount of FT as intended, without truncating decimal places or causing rounding errors.

Actual Behavior:
The amount sent may not match the expected full amount due to precision issues.

**Comment by JeffreyDoyle** [comment]
@Peppermint1020 To double check completion before closing this issue

**Comment by Peppermint1020** [comment]
Tested on Android r2.6.0.

When I moved the max value of stFlow, not all of it was transferred. Only the amount up to two decimal places was moved.

@jaymengxy

**Comment by Peppermint1020** [comment]
Tested on Android internal version i1.6.12.
When I moved the max value of BETA.classic token , all of it was transferred.
https://evm.flowscan.io/tx/0x2ec802c623e1bf4a6e3a3f2e1b96e9292363a7ba1587d733e036b2a347065a8a
When I moved the max value of stflow token , all of it was transferred.
https://evm.flowscan.io/tx/0x407957122cbb60a898be4334ffa7f9f4aa232388e198f01fa680e00a3cf7cc2b
