### ISSUE TITLE
[BUG]No Response When Clicking Redeem Button in Flow Mobile (Android)

### ISSUE THREAD

**Issue by Peppermint1020** [Outblock/FRW-Android#406]
**Description:**
This Bug reported by Flow team. 

When attempting to claim rewards in the Flow Wallet mobile app on Android (2.5.10), there is no response when clicking the "Redeem" button. All other buttons on the page work as expected, but the "Redeem" button does not trigger any action. It's unclear whether the issue is client-side or related to the wallet.

**Expected Behavior:**

The "Redeem" button should trigger the appropriate action to claim rewards.

**Actual Behavior:**

Clicking the "Redeem" button results in no response, and the button does not perform any action.

**Environment:**

Flow Wallet version: 2.5.10
[debug_messages (1).txt](https://github.com/user-attachments/files/17628072/debug_messages.1.txt)

**Comment by lmcmz** [comment]
Issues fixed, close for now
