### ISSUE TITLE
[Backup] Create Backup UI

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#41]

**Comment by Peppermint1020** [comment]
The test version is dev mode android version vDebug. The vision of test phone is Android 17.

There some UI difference between actual dev app and UI design.
1. In UI design we have backup process shown by icons, but not in dev app.
In UI design ,we have:


![Image](https://github.com/Outblock/FRW-Android/assets/87978227/2c566540-c876-4604-95c7-dd0830bd023c)

In our dev app, it shown as:

![Image](https://github.com/Outblock/FRW-Android/assets/87978227/7da9e6f7-9b2e-4150-a337-137a865010b5)

2. The device backup did not have scan QR code with mobile app.
The UI design is:

![Image](https://github.com/Outblock/FRW-Android/assets/87978227/842fb087-0a8f-42d8-8645-0ad268123480)

The actual behaviour is:


![Image](https://github.com/Outblock/FRW-Android/assets/87978227/0438717e-c396-4e9d-8111-63e3f3e457f4)
