### ISSUE TITLE
[FEATURE] Account storage alert

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#419]
### Issue to be solved

Background:
https://github.com/Outblock/FRW/issues/61

#### Get Storage and Available Balance Info

Our script API returns `getAccountInfo` cadence, which allow wallet to get the storage info under an account.
```swift
access(all) struct Result {
  access(all) let address: Address
  access(all) let balance: UFix64
  access(all) let availableBalance: UFix64
  access(all) let storageUsed: UInt64
  access(all) let storageCapacity: UInt64
  access(all) let storageFlow: UFix64,
}
```
If `storageCapacity - storageUsed < 10000` then it's insufficient storage

#### Notification
Currently, we use firebase remote config to control the notification messages. It use `news` at the moment.
For insufficient storage alert, we gonna add a new condition flag `insufficientStorage`, which user reach storage limit. 

#### Onchain Interaction
Any onchain Interaction, wallet need do a async check whether the storage is sufficient or not.

If it's send Flow Token or move action ( move fee ), the balance will be affected we need take count of the sending or move fee balance.  ( availableBalance - sent amount ) < 0.001
Other onchain Interaction, we only do the availableBalance check.

Following is the list of storage warning in action button:

1. Move token
2. Move NFT
3. Send Token
4. Send NFT
5. Sign Transaction on browser
6. Sign Transaction on WalletConnect

#### Transaction Listener
Every transaction submitted to the chain, the wallet will listen the callback. So when there is `storageCapacityExceeded`.
we need show an global alert telling user that the last transaction was failing due to storage.

#### Storage Usage Card
Storage info card need to be displayed only under FLOW token detail page.

Figma: 
https://www.figma.com/design/mSr5uIApRJNrpkmN0YNuD6/FLOW-REF-Mobile-Design-v2.0.0?node-id=35558-33202&t=eegpA2haFKcXcypT-1

**Comment by Peppermint1020** [comment]
Following is the list of storage warning in action button:

- [ ] Move token
- [ ] Move NFT
- [ ] Send Token
- [ ] Send NFT
- [ ] Sign Transaction on browser
- [ ] Sign Transaction on WalletConnect

Issues:
(1) When click "learn it more" link, no page redirection.
(2) Storage limit alert not pop up, when have this error: https://www.flowscan.io/tx/5322ad883ef8e408f1f3e9e7072a38123e15361132611ef12484c1e6832c3223
(3) EVM account display flow token amount incorrectly. I have 80 flow token in my evm wallet, but android display 0.

**Comment by Peppermint1020** [comment]
After last Friday's meeting, we agreed to use a simpler approach to alert users.

**Comment by Peppermint1020** [comment]
This feature already add in Android dev 60 (i1.7.1)
