### ISSUE TITLE
[Restore] Restore with iCloud keychain

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#48]

**Comment by Peppermint1020** [comment]
This function is complete in the dev mode IOS version 2.0.4(2). The vision of test phone is IOS 17.1.2

The whole process is attached below. User can restore by iCloud keychain and login in their account.


https://github.com/Outblock/FRW-Android/assets/87978227/fefbc45a-bec6-47f1-a96d-e56403041786

Note: need to update to new UI design.
