### ISSUE TITLE
Device List Page

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#8]

**Comment by Peppermint1020** [comment]
The test version is dev mode Android version VDebug. The vision of test phone is Android 17.

The  most functions work fine in this page.
We just miss two function that mentioned in UI design.
1.scan QR code to add device.
2.delete device



![Image](https://github.com/Outblock/FRW-Android/assets/87978227/86c4f69b-6e65-4df8-b9a2-fa72da08aab4)

**Comment by Peppermint1020** [comment]
The above UI issues already solved in Android dev version vDebug.
The screenshots are attached below.


![Image](https://github.com/Outblock/FRW-Android/assets/87978227/90055bef-ec0d-4629-aa7b-fb98008ecea3)



![Image](https://github.com/Outblock/FRW-Android/assets/87978227/14b194b9-87fc-4d25-b52e-383aa9645fa5)
