### ISSUE TITLE
UI - Move FT Assets between VM

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#89]

**Comment by Peppermint1020** [comment]
This UI and function already build in flow wallet android dev version i1.0.2
Flow tokens can be transfer between previewnet and EVM.
The demo video are attached below.


https://github.com/Outblock/FRW-Android/assets/87978227/cd786985-1169-4c7b-b11c-397850154c7b
https://github.com/Outblock/FRW-Android/assets/87978227/93a4e354-cf01-4930-9bb3-9ef4c038de20
