### ISSUE TITLE
Key List Page

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#9]

**Comment by Peppermint1020** [comment]
The test version is dev mode Android version VDebug. The vision of test phone is Android 17.

The revoked function is not work. When I click revoked, the key still active in the list. The process video attached below.



https://github.com/Outblock/FRW-Android/assets/87978227/f881d54a-a377-4b11-b1c7-a55c9e7ebeb6

**Comment by Peppermint1020** [comment]
This issue already been solved in Android version vDebug.
Now keys can be revoked successfully. 
The video is attached below.


https://github.com/Outblock/FRW-Android/assets/87978227/a5ba9d94-dacc-4487-84c1-0f42f19165df
