### ISSUE TITLE
EVM Welcome Page

### ISSUE THREAD

**Issue by lmcmz** [Outblock/FRW-Android#93]

**Comment by Peppermint1020** [comment]
This page already add in flow wallet android dev version i1.0.2
And user can click enable button to activate evm account.
1. There is no link for learn more button.
2. Color of text Flow EVM is different with UI design.
![Image](https://github.com/Outblock/FRW-Android/assets/87978227/45405f73-e090-40c0-a216-9dca02dc12d0)

UI design is attached below.

![Image](https://github.com/Outblock/FRW-Android/assets/87978227/79ad71cc-b1e0-412c-8fc0-84c1617924e9)
